# Generated by Django 3.0.6 on 2020-07-06 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_n', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilEntreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entr', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(choices=[('CPGE/BTS/DEUG/...', 'CPGE/BTS/DEUG/...'), ('Licence', 'Licence '), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Entreprise.ProfilEntreprise')),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Entreprise.Poste')),
            ],
        ),
    ]
