# Generated by Django 3.0.6 on 2020-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='diplome',
            field=models.CharField(choices=[('', '(Select)'), ('CPGE/BTS/DEUG/...', 'CPGE/BTS/DEUG/...'), ('Licence', 'Licence '), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20, null=True),
        ),
    ]
