# Generated by Django 3.0.6 on 2020-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0002_auto_20200711_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='diplome',
            field=models.CharField(choices=[('', '(Degree)'), ('Bachelor', 'Bachelor '), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20, null=True),
        ),
    ]
