# Generated by Django 3.0.6 on 2020-06-21 13:21

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ecole', models.CharField(max_length=50, null=True)),
                ('classement', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, null=True)),
                ('prenom', models.CharField(max_length=20, null=True)),
                ('date_n', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('C', 'célibataire'), ('M', 'marié(e)'), ('V', 'veuf(ve)'), ('D', 'divorcé(e)')], max_length=1, null=True)),
                ('nationalite', models.CharField(max_length=20, null=True)),
                ('pays', django_countries.fields.CountryField(max_length=2, null=True)),
                ('ville', models.CharField(max_length=20, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet_realise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_projet', models.IntegerField(null=True)),
                ('description_projet', models.TextField(blank=True, null=True)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(choices=[('A1', 'découverte'), ('A2', 'usuel'), ('B1', 'niveau seuil'), ('B2', 'niveau avancé'), ('C1', 'autonome'), ('C2', 'maîtrise')], max_length=2, null=True)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Experience_Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField(null=True)),
                ('annee_fin', models.IntegerField(null=True)),
                ('description_exp_pro', models.TextField(blank=True, null=True)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation', models.CharField(max_length=100, null=True)),
                ('titre_cert', models.CharField(max_length=50, null=True)),
                ('date_cert', models.IntegerField(null=True)),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_debut', models.IntegerField(null=True)),
                ('annee_fin', models.IntegerField(null=True)),
                ('type_diplome', models.CharField(choices=[('1', 'CPGE/BTS/DEUG/...'), ('2', 'Licence '), ('3', 'Master'), ('4', 'Doctorat')], max_length=1, null=True)),
                ('description_academic', models.TextField(blank=True, null=True)),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Candidat.Ecole')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
    ]
