# Generated by Django 3.0.6 on 2020-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0003_auto_20200702_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sex',
            field=models.CharField(choices=[('', '(Gender)'), ('Homme', 'Male'), ('Femme', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(choices=[('', '(Status)'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=12, null=True),
        ),
    ]
