# Generated by Django 3.0.6 on 2020-07-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0005_auto_20200719_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=50)),
                ('openness', models.CharField(blank=True, max_length=20)),
                ('conscientiousness', models.CharField(blank=True, max_length=20)),
                ('extraversion', models.CharField(blank=True, max_length=20)),
                ('agreeableness', models.CharField(blank=True, max_length=20)),
                ('neuroticism', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScorePersonalite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScoreOp', models.IntegerField(blank=True, default=0)),
                ('ScoreCon', models.IntegerField(blank=True, default=0)),
                ('ScoreExt', models.IntegerField(blank=True, default=0)),
                ('ScoreAgr', models.IntegerField(blank=True, default=0)),
                ('ScoreNeu', models.IntegerField(blank=True, default=0)),
                ('Profil', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Candidat.Profil')),
            ],
        ),
        migrations.DeleteModel(
            name='Personalite',
        ),
    ]
