# Generated by Django 3.0.6 on 2020-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0009_auto_20200720_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
