# Generated by Django 3.0.6 on 2020-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0010_auto_20200720_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='specialite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='ecole',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='type_diplome',
            field=models.CharField(choices=[('', '(Degree)'), ('Bachelor', 'Bachelor '), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
    ]
