# Generated by Django 3.0.6 on 2020-07-23 17:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0012_auto_20200723_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='date_n',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nationalite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '(Gender)'), ('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='specialite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='status',
            field=models.CharField(blank=True, choices=[('', '(Status)'), ('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ville',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
