# Generated by Django 3.0.6 on 2020-07-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprise', '0003_auto_20200723_1806'),
        ('Candidat', '0013_auto_20200723_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='specialite',
        ),
        migrations.AddField(
            model_name='profil',
            name='poste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Entreprise.Poste'),
        ),
    ]
