# Generated by Django 3.0.6 on 2020-07-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0015_auto_20200725_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience_pro',
            old_name='nbr_annnee',
            new_name='nbr_annee',
        ),
    ]
