# Generated by Django 3.0.6 on 2020-07-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0016_auto_20200725_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='nbr_annee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
