# Generated by Django 3.0.6 on 2020-07-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0017_profil_nbr_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='type_diplome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
