# Generated by Django 3.0.6 on 2020-08-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidat', '0019_auto_20200811_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil_pic',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to=''),
        ),
    ]
